[package]
name = "lens-sl"
version = "0.1.0"
edition = "2024"
# We have multiple binaries in this package, use the main file as the default one.
default-run = "lens-sl"

[dependencies]
bitflags = { version = "2.10.0", features = ["serde"] }
derive_more = { version = "2.1.1", features = ["full"] }
functionality = "1.0.0"
itertools = "0.14"
rustc-hash = "2.1.1"
smtlib = "0.3.0"
# Most standard rust serialization
serde = { version = "1", features = ["derive"] }
# A should-be-quick-enough binary format
postcard = { version = "1.1", features = ["use-std"] }
humantime = "2.3"

[dev-dependencies]
proptest = { version = "1.9.0", features = ["attr-macro"] }
proptest-derive = "0.7.0"

[profile.release]
debug = true

[profile.test.package.proptest]
opt-level = 3

[profile.test.package.rand_chacha]
opt-level = 3

[profile.test.package.postcard]
opt-level = 3
[profile.dev.package.postcard]
opt-level = 3

[profile.test.package.serde]
opt-level = 3
[profile.dev.package.serde]
opt-level = 3
