[package]
name = "lens-sl"
version = "0.1.0"
edition = "2024"
# We have multiple binaries in this package, use the main file as the default one.
default-run = "lens-sl"

[dependencies]
arbitrary-int = { git = "https://github.com/danlehmann/arbitrary-int", rev = "0b888b8" }
bitflags = "2.10.0"
derive_more = { version = "2.1.1", features = ["full"] }
functionality = "1.0.0"
# This is the same version as used by arbitrary-int above
rustc-hash = "2.1.1"

[dev-dependencies]
proptest = { version = "1.9.0", features = ["attr-macro"] }
proptest-derive = "0.7.0"

[profile.release]
debug = true

[profile.test.package.proptest]
opt-level = 3

[profile.test.package.rand_chacha]
opt-level = 3
